### ISSUE TITLE
I would like to be a maintainer

### ISSUE THREAD

**Issue by faeghe-hajiabadi** [reactjs/fa.react.dev#351]
Hi,
Please help me to be a main participator of this repo as now I have more time and energy and I can be helpful
this is my last [pr](https://github.com/reactjs/fa.react.dev/pull/350):

**Comment by faeghe-hajiabadi** [comment]
Also please help me to understand how to review for the best result, should I consider UI changes as well? or will you review at a higher level? I really think we need a more simple introduction in English for UI changes for new jopiners!
Thanks

**Comment by rezvani2647** [comment]
@faeghe-hajiabadi please send me your email address so we can have a Google Meet session and discuss this mater.

**Comment by faeghe-hajiabadi** [comment]
> @faeghe-hajiabadi please send me your email address so we can have a Google Meet session and discuss this mater.

Here is my email: Faeghe.hajiabadi@gmail.com

**Comment by rezvani2647** [comment]
welcome to React community.
