### ISSUE TITLE
Sharing State Between Components

### ISSUE THREAD

**Issue by faeghe-hajiabadi** [reactjs/fa.react.dev#357]

**Comment by Ehsan-Yari** [comment]
hi @faeghe-hajiabadi 

I just translated this section and if there are any changes required, please let me know. thank you :)

**Comment by faeghe-hajiabadi** [comment]
> hi @faeghe-hajiabadi
> 
> I just translated this section and if there are any changes required, please let me know. thank you :)
please raise pull request and mention the pr number?
حمثش
