### ISSUE TITLE
پیشنهاد برای نگارش بهتر متن

### ISSUE THREAD

**Issue by sir-kokabi** [reactjs/fa.react.dev#407]
### Summary

-

### Details

سلام.
تو [این صفحه](https://github.com/reactjs/fa.react.dev/blob/main/TRANSLATION.md)، برای برخی از کلمات که معادلِ فارسی نداره، پیشنهاد شده همون شکلِ انگلیسی به کار بره.

من اینجا دو تا پیشنهاد دارم:

۱. معمولاً در شیوه‌نامه‌ها، برای حفظ یکدستی و کاهش هزینه‌های بعدی، از به‌کارگیری واژه‌های غیرصریح مثل «پیشنهاد دادن» که به مشارکت‌کننده حق اختیار می‌ده اجتناب می‌شه. پیشنهاد می‌کنم اینجا تکلیف رو روشن کنید که اصلِ واژهٔ انگلیسی به کار بره یا نه. چون اینجوری ممکنه بعضی‌ها بنویسن «ایمپورت» و بعضی‌ها بنویسن «import» و این باعث نایکدستی و کاهش خوانایی متن می‌شه.

۲. پیشنهاد می‌کنم برای بعضی از کلمات که شکل فینگلیش نسبتاً پذیرفته‌شده‌ای دارن همون شکل فینگلیش استفاده بشه. مثلاً: ایمپورت، ویو، استیت، تایم‌استمپ، اچ‌تی‌ام‌ال، ای‌پی‌آی، جی‌اس‌ایکس و ... . در متنی که بارها از واژهٔ state و import استفاده شده، هم ظاهر متن، خراب می‌شه و هم خواننده ناچاره بارها بین فارسی و انگلیسی (حتی برای لحظه‌ای درنگ) جابه‌جا بشه که جالب نیست.

**Comment by rezvani2647** [comment]
سلام دوست عزیز شما میتونین در [این](https://github.com/reactjs/fa.react.dev/issues/41) لینک نظراتت و با همه به اشتراک بگذارین. 
در کل با یکپارچه بودن موافق هستم.
 اما فکر می‌کنم در لینکی که فرستادم و قسمت واژه نامه به این موارد اشاره شده باشه. اگر نه اونجا میشه مورد بحث قرار داد.
